import { Routes } from '@angular/router';
import { PageSeo } from './shared/seo';

// GENERATED by scripts/import-legacy.mjs from the legacy CodeKit site. Edit the Angular pages
// directly going forward (src/app/pages/**); re-running the importer overwrites them.
export const routes: Routes = [
  {
    path: '',
    loadComponent: () => import('./pages/home/home.component').then((m) => m.HomeComponent),
    title: "Mikael Cedergren | Art Director, Content Strategist & User Experience Designer",
    data: { seo: { path: '/', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions." } satisfies PageSeo },
  },
  {
    path: 'about',
    loadComponent: () => import('./pages/about/about.component').then((m) => m.AboutComponent),
    title: "About | Mikael Cedergren",
    data: { seo: { path: '/about/', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions." } satisfies PageSeo },
  },
  {
    path: 'resume',
    loadComponent: () => import('./pages/resume/resume.component').then((m) => m.ResumeComponent),
    title: "Resume | Mikael Cedergren",
    data: { seo: { path: '/resume/', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions." } satisfies PageSeo },
  },
  {
    path: 'concepts',
    loadComponent: () => import('./pages/concepts/concepts.component').then((m) => m.ConceptsComponent),
    title: "Concepts | Mikael Cedergren",
    data: { seo: { path: '/concepts/', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions." } satisfies PageSeo },
  },
  {
    path: 'blog',
    loadComponent: () => import('./pages/blog/blog.component').then((m) => m.BlogIndexComponent),
    title: "Blog | Mikael Cedergren",
    data: { seo: { path: '/blog/', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions." } satisfies PageSeo },
  },
  {
    path: 'blog/posts/brainstorming.html',
    loadComponent: () => import('./pages/blog/posts/brainstorming.component').then((m) => m.BrainstormingComponent),
    title: "Unlocking Creativity - A Simple Guide to Brainstorming | Mikael Cedergren",
    data: { seo: { path: '/blog/posts/brainstorming.html', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions.", ogType: 'article' } satisfies PageSeo },
  },
  {
    path: 'blog/posts/creative-leadership.html',
    loadComponent: () => import('./pages/blog/posts/creative-leadership.component').then((m) => m.CreativeLeadershipComponent),
    title: "How to Make Your Creative Team Love the Work | Mikael Cedergren",
    data: { seo: { path: '/blog/posts/creative-leadership.html', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions.", ogType: 'article' } satisfies PageSeo },
  },
  {
    path: 'blog/posts/letter-from-a-user.html',
    loadComponent: () => import('./pages/blog/posts/letter-from-a-user.component').then((m) => m.LetterFromAUserComponent),
    title: "Letter from a user | Mikael Cedergren",
    data: { seo: { path: '/blog/posts/letter-from-a-user.html', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions.", ogType: 'article' } satisfies PageSeo },
  },
  {
    path: 'blog/posts/relative-vs-absolute-time.html',
    loadComponent: () => import('./pages/blog/posts/relative-vs-absolute-time.component').then((m) => m.RelativeVsAbsoluteTimeComponent),
    title: "Relative vs absolute time | Mikael Cedergren",
    data: { seo: { path: '/blog/posts/relative-vs-absolute-time.html', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions.", ogType: 'article' } satisfies PageSeo },
  },
  {
    path: 'blog/posts/the-key-to-understanding-your-client.html',
    loadComponent: () => import('./pages/blog/posts/the-key-to-understanding-your-client.component').then((m) => m.TheKeyToUnderstandingYourClientComponent),
    title: "The Key to Understanding Your Client | Mikael Cedergren",
    data: { seo: { path: '/blog/posts/the-key-to-understanding-your-client.html', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions.", ogType: 'article' } satisfies PageSeo },
  },
  {
    path: 'blog/posts/the-most-common-ux-mistakes-and-how-to-avoid-them.html',
    loadComponent: () => import('./pages/blog/posts/the-most-common-ux-mistakes-and-how-to-avoid-them.component').then((m) => m.TheMostCommonUxMistakesAndHowToAvoidThemComponent),
    title: "The Most Common UX Mistakes | Mikael Cedergren",
    data: { seo: { path: '/blog/posts/the-most-common-ux-mistakes-and-how-to-avoid-them.html', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions.", ogType: 'article' } satisfies PageSeo },
  },
  {
    path: 'blog/posts/ui-and-ux.html',
    loadComponent: () => import('./pages/blog/posts/ui-and-ux.component').then((m) => m.UiAndUxComponent),
    title: "UI and UX - Two Sides of the Same Coin | Mikael Cedergren",
    data: { seo: { path: '/blog/posts/ui-and-ux.html', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions.", ogType: 'article' } satisfies PageSeo },
  },
  {
    path: 'blog/posts/ux-directives.html',
    loadComponent: () => import('./pages/blog/posts/ux-directives.component').then((m) => m.UxDirectivesComponent),
    title: "UX Directives - A Simple Guide to how to Create Good UX | Mikael Cedergren",
    data: { seo: { path: '/blog/posts/ux-directives.html', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions.", ogType: 'article' } satisfies PageSeo },
  },
  {
    path: 'blog/posts/whats-a-designer-and-why-do-you-need-one.html',
    loadComponent: () => import('./pages/blog/posts/whats-a-designer-and-why-do-you-need-one.component').then((m) => m.WhatsADesignerAndWhyDoYouNeedOneComponent),
    title: "What’s a Designer, and Why Do You Need One? | Mikael Cedergren",
    data: { seo: { path: '/blog/posts/whats-a-designer-and-why-do-you-need-one.html', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions.", ogType: 'article' } satisfies PageSeo },
  },
  {
    path: 'blog/posts/why-natural-language-matters.html',
    loadComponent: () => import('./pages/blog/posts/why-natural-language-matters.component').then((m) => m.WhyNaturalLanguageMattersComponent),
    title: "Why natural language matters | Mikael Cedergren",
    data: { seo: { path: '/blog/posts/why-natural-language-matters.html', description: "Explore the work of Mikael Cedergren, a designer focused on simple, effective, and meaningful creative solutions.", ogType: 'article' } satisfies PageSeo },
  },
  {
    path: '**',
    loadComponent: () => import('./pages/not-found/not-found.component').then((m) => m.NotFoundComponent),
    title: 'Page not found | Mikael Cedergren',
    data: { seo: { path: '/404', description: 'Page not found.', noindex: true } satisfies PageSeo },
  },
];
